# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0002_mood'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thought',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.TextField(max_length=100)),
                ('think', models.TextField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Mood',
        ),
    ]
